const items = {
ammo: [
    { id: 'ammo.shotgun', name: '12 Gauge Buckshot' },
    { id: 'ammo.shotgun.fire', name: '12 Gauge Incendiary Shell' },
    { id: 'ammo.shotgun.slug', name: '12 Gauge Slug' },
    { id: 'ammo.grenadelauncher.he', name: '40mm HE Grenade' },
    { id: 'ammo.grenadelauncher.buckshot', name: '40mm Shotgun Round' },
    { id: 'ammo.grenadelauncher.smoke', name: '40mm Smoke Grenade' },
    { id: 'ammo.rifle', name: '5.56 Rifle Ammo' },
    { id: 'ammo.rifle.explosive', name: 'Explosive 5.56 Rifle Ammo' },
    { id: 'ammo.handmade.shell', name: 'Handmade Shell' },
    { id: 'ammo.rocket.hv', name: 'High Velocity Rocket' },
    { id: 'ammo.rifle.hv', name: 'HV 5.56 Rifle Ammo' },
    { id: 'ammo.pistol.hv', name: 'HV Pistol Ammo' },
    { id: 'ammo.rifle.incendiary', name: 'Incendiary 5.56 Rifle Ammo' },
    { id: 'ammo.pistol.fire', name: 'Incendiary Pistol Bullet' },
    { id: 'ammo.rocket.fire', name: 'Incendiary Rocket' },
    { id: 'ammo.nailgun.nails', name: 'Nailgun Nails' },
    { id: 'ammo.pistol', name: 'Pistol Bullet' },
    { id: 'ammo.rocket.basic', name: 'Rocket' },
    { id: 'submarine.torpedo.straight', name: 'Torpedo' }
],
weapons: [
    { id: 'weapon.mod.burstmodule', name: 'Burst Module' },
    { id: 'weapon.mod.extendedmags', name: 'Extended Magazine' },
    { id: 'weapon.mod.holosight', name: 'Holosight' },
    { id: 'weapon.mod.muzzleboost', name: 'Muzzle Boost' },
    { id: 'weapon.mod.muzzlebrake', name: 'Muzzle Brake' },
    { id: 'weapon.mod.simplesight', name: 'Simple Handmade Sight' },
    { id: 'weapon.mod.silencer', name: 'Silencer' },
    { id: 'weapon.mod.flashlight', name: 'Weapon Flashlight' },
    { id: 'weapon.mod.lasersight', name: 'Weapon Lasersight' },
    { id: 'rifle.ak', name: 'Assault Rifle' },
    { id: 'grenade.beancan', name: 'Beancan Grenade' },
    { id: 'rifle.bolt', name: 'Bolt Action Rifle' },
    { id: 'bone.club', name: 'Bone Club' },
    { id: 'knife.bone', name: 'Bone Knife' },
    { id: 'knife.combat', name: 'Combat Knife' },
    { id: 'bow.compound', name: 'Compound Bow' },
    { id: 'crossbow', name: 'Crossbow' },
    { id: 'smg.2', name: 'Custom SMG' },
    { id: 'shotgun.double', name: 'Double Barrel Shotgun' },
    { id: 'pistol.eoka', name: 'Eoka Pistol' },
    { id: 'grenade.f1', name: 'F1 Grenade' },
    { id: 'flamethrower', name: 'Flame Thrower' },
    { id: 'grenade.flashbang', name: 'Flashbang' },
    { id: 'hmlmg', name: 'HMLMG' },
    { id: 'bow.hunting', name: 'Hunting Bow' },
    { id: 'rifle.l96', name: 'L96 Rifle' },
    { id: 'longsword', name: 'Longsword' },
    { id: 'rifle.lr300', name: 'LR-300 Assault Rifle' },
    { id: 'lmg.m249', name: 'M249' },
    { id: 'rifle.m39', name: 'M39 Rifle' },
    { id: 'pistol.m92', name: 'M92 Pistol' },
    { id: 'mace', name: 'Mace' },
    { id: 'machete', name: 'Machete' },
    { id: 'grenade.molotov', name: 'Molotov Cocktail' },
    { id: 'smg.mp5', name: 'MP5A4' },
    { id: 'multiplegrenadelauncher', name: 'Multiple Grenade Launcher' },
    { id: 'pistol.nailgun', name: 'Nailgun' },
    { id: 'paddle', name: 'Paddle' },
    { id: 'pistol.prototype17', name: 'Prototype 17' },
    { id: 'shotgun.pump', name: 'Pump Shotgun' },
    { id: 'pistol.python', name: 'Python Revolver' },
    { id: 'pistol.revolver', name: 'Revolver' },
    { id: 'rocket.launcher', name: 'Rocket Launcher' },
    { id: 'salvaged.cleaver', name: 'Salvaged Cleaver' },
    { id: 'salvaged.sword', name: 'Salvaged Sword' },
    { id: 'pistol.semiauto', name: 'Semi-Automatic Pistol' },
    { id: 'rifle.semiauto', name: 'Semi-Automatic Rifle' },
    { id: 'shotgun.spas12', name: 'Spas-12 Shotgun' },
    { id: 'speargun', name: 'Speargun' },
    { id: 'spear.stone', name: 'Stone Spear' },
    { id: 'smg.thompson', name: 'Thompson' },
    { id: 'shotgun.waterpipe', name: 'Waterpipe Shotgun' },
    { id: 'spear.wooden', name: 'Wooden Spear' }
],
construction: [
    { id: 'door.hinged.toptier', name: 'Armored Door' },
    { id: 'door.double.hinged.toptier', name: 'Armored Double Door' },
    { id: 'barricade.woodwire', name: 'Barbed Wooden Barricade' },
    { id: 'building.planner', name: 'Building Plan' },
    { id: 'wall.frame.fence', name: 'Chainlink Fence' },
    { id: 'wall.frame.fence.gate', name: 'Chainlink Fence Gate' },
    { id: 'lock.code', name: 'Code Lock' },
    { id: 'barricade.concrete', name: 'Concrete Barricade' },
    { id: 'floor.grill', name: 'Floor Grill' },
    { id: 'floor.triangle.grill', name: 'Floor Triangle Grill' },
    { id: 'wall.frame.garagedoor', name: 'Garage Door' },
    { id: 'gates.external.high.stone', name: 'High External Stone Gate' },
    { id: 'gates.external.high.wood', name: 'High External Wooden Gate' },
    { id: 'wall.external.high.stone', name: 'High External Stone Wall' },
    { id: 'wall.external.high', name: 'High External Wooden Wall' },
    { id: 'lock.key', name: 'Key Lock' },
    { id: 'floor.ladder.hatch', name: 'Ladder Hatch' },
    { id: 'water.catcher.large', name: 'Large Water Catcher' },
    { id: 'barricade.metal', name: 'Metal Barricade' },
    { id: 'shutter.metal.embrasure.a', name: 'Metal Horizontal Embrasure' },
    { id: 'wall.frame.shopfront.metal', name: 'Metal Shop Front' },
    { id: 'shutter.metal.embrasure.b', name: 'Metal Vertical Embrasure' },
    { id: 'wall.window.bars.metal', name: 'Metal Window Bars' },
    { id: 'wall.frame.netting', name: 'Netting' },
    { id: 'wall.frame.cell.gate', name: 'Prison Cell Gate' },
    { id: 'wall.frame.cell', name: 'Prison Cell Wall' },
    { id: 'wall.window.bars.toptier', name: 'Reinforced Glass Window' },
    { id: 'barricade.sandbags', name: 'Sandbag Barricade' },
    { id: 'door.hinged.metal', name: 'Sheet Metal Door' },
    { id: 'door.double.hinged.metal', name: 'Sheet Metal Double Door' },
    { id: 'wall.frame.shopfront', name: 'Shop Front' },
    { id: 'water.catcher.small', name: 'Small Water Catcher' },
    { id: 'barricade.stone', name: 'Stone Barricade' },
    { id: 'wall.window.glass.reinforced', name: 'Strengthened Glass Window' },
    { id: 'cupboard.tool', name: 'Tool Cupboard' },
    { id: 'floor.triangle.ladder.hatch', name: 'Triangle Ladder Hatch' },
    { id: 'watchtower.wood', name: 'Watch Tower' },
    { id: 'door.double.hinged.wood', name: 'Wood Double Door' },
    { id: 'shutter.wood.a', name: 'Wood Shutters' },
    { id: 'barricade.wood', name: 'Wooden Barricade' },
    { id: 'barricade.wood.cover', name: 'Wooden Barricade Cover' },
    { id: 'door.hinged.wood', name: 'Wooden Door' },
    { id: 'ladder.wooden.wall', name: 'Wooden Ladder' },
    { id: 'wall.window.bars.wood', name: 'Wooden Window Bars' }
],
items: [
    { id: 'bbq', name: 'Barbeque' },
    { id: 'bed', name: 'Bed' },
    { id: 'botabag', name: 'Bota Bag' },
    { id: 'campfire', name: 'Camp Fire' },
    { id: 'chair', name: 'Chair' },
    { id: 'dropbox', name: 'Drop Box' },
    { id: 'fridge', name: 'Fridge' },
    { id: 'furnace', name: 'Furnace' },
    { id: 'hitchtroughcombo', name: 'Hitch & Trough' },
    { id: 'kayak', name: 'Kayak' },
    { id: 'lantern', name: 'Lantern' },
    { id: 'furnace.large', name: 'Large Furnace' },
    { id: 'planter.large', name: 'Large Planter Box' },
    { id: 'box.wooden.large', name: 'Large Wood Box' },
    { id: 'locker', name: 'Locker' },
    { id: 'mailbox', name: 'Mail Box' },
    { id: 'mixingtable', name: 'Mixing Table' },
    { id: 'box.repair.bench', name: 'Repair Bench' },
    { id: 'research.table', name: 'Research Table' },
    { id: 'rhib', name: 'RHIB' },
    { id: 'rowboat', name: 'Rowboat' },
    { id: 'rug.bear', name: 'Rug Bear Skin' },
    { id: 'rug', name: 'Rug' },
    { id: 'shelves', name: 'Salvaged Shelves' },
    { id: 'skull_fire_pit', name: 'Skull Fire Pit' },
    { id: 'sleepingbag', name: 'Sleeping Bag' },
    { id: 'planter.small', name: 'Small Planter Box' },
    { id: 'small.oil.refinery', name: 'Small Oil Refinery' },
    { id: 'stash.small', name: 'Small Stash' },
    { id: 'fireplace.stone', name: 'Stone Fireplace' },
    { id: 'fishtrap.small', name: 'Survival Fish Trap' },
    { id: 'table', name: 'Table' },
    { id: 'tunalight', name: 'Tuna Can Lamp' },
    { id: 'vending.machine', name: 'Vending Machine' },
    { id: 'water.barrel', name: 'Water Barrel' },
    { id: 'water.purifier', name: 'Water Purifier' },
    { id: 'box.wooden', name: 'Wood Storage Box' },
    { id: 'workbench1', name: 'Workbench Level 1' },
    { id: 'workbench2', name: 'Workbench Level 2' },
    { id: 'workbench3', name: 'Workbench Level 3' }
],
resources: [
    { id: 'fat.animal', name: 'Animal Fat' },
    { id: 'bone.fragments', name: 'Bone Fragments' },
    { id: 'cctv.camera', name: 'CCTV Camera' },
    { id: 'charcoal', name: 'Charcoal' },
    { id: 'cloth', name: 'Cloth' },
    { id: 'crude.oil', name: 'Crude Oil' },
    { id: 'diesel_barrel', name: 'Diesel Fuel' },
    { id: 'can.beans.empty', name: 'Empty Can Of Beans' },
    { id: 'can.tuna.empty', name: 'Empty Tuna Can' },
    { id: 'explosives', name: 'Explosives' },
    { id: 'fertilizer', name: 'Fertilizer' },
    { id: 'gunpowder', name: 'Gun Powder' },
    { id: 'metal.refined', name: 'High Quality Metal' },
    { id: 'hq.metal.ore', name: 'High Quality Metal Ore' },
    { id: 'horsedung', name: 'Horse Dung' },
    { id: 'skull.human', name: 'Human Skull' },
    { id: 'leather', name: 'Leather' },
    { id: 'lowgradefuel', name: 'Low Grade Fuel' },
    { id: 'metal.fragments', name: 'Metal Fragments' },
    { id: 'metal.ore', name: 'Metal Ore' },
    { id: 'plantfiber', name: 'Plant Fiber' },
    { id: 'water.salt', name: 'Salt Water' },
    { id: 'scrap', name: 'Scrap' },
    { id: 'stones', name: 'Stones' },
    { id: 'sulfur.ore', name: 'Sulfur Ore' },
    { id: 'sulfur', name: 'Sulfur' },
    { id: 'targeting.computer', name: 'Targeting Computer' },
    { id: 'water', name: 'Water' },
    { id: 'skull.wolf', name: 'Wolf Skull' },
    { id: 'wood', name: 'Wood' }
],
attire: [
    { id: 'mask.bandana', name: 'Bandana Mask' },
    { id: 'barrelcostume', name: 'Barrel Costume' },
    { id: 'hat.cap', name: 'Baseball Cap' },
    { id: 'hat.beenie', name: 'Beanie Hat' },
    { id: 'bone.armor.suit', name: 'Bone Armor' },
    { id: 'deer.skull.mask', name: 'Bone Helmet' },
    { id: 'hat.boonie', name: 'Boonie Hat' },
    { id: 'shoes.boots', name: 'Boots' },
    { id: 'bucket.helmet', name: 'Bucket Helmet' },
    { id: 'burlap.gloves.new', name: 'Burlap Gloves' },
    { id: 'burlap.headwrap', name: 'Burlap Headwrap' },
    { id: 'burlap.shirt', name: 'Burlap Shirt' },
    { id: 'burlap.shoes', name: 'Burlap Shoes' },
    { id: 'burlap.trousers', name: 'Burlap Trousers' },
    { id: 'hat.candle', name: 'Candle Hat' },
    { id: 'coffeecan.helmet', name: 'Coffee Can Helmet' },
    { id: 'cratecostume', name: 'Crate Costume' },
    { id: 'diving.fins', name: 'Diving Fins' },
    { id: 'diving.mask', name: 'Diving Mask' },
    { id: 'diving.tank', name: 'Diving Tank' },
    { id: 'boots.frog', name: 'Frog Boots' },
    { id: 'hazmatsuit', name: 'Hazmat Suit' },
    { id: 'heavy.plate.helmet', name: 'Heavy Plate Helmet' },
    { id: 'heavy.plate.jacket', name: 'Heavy Plate Jacket' },
    { id: 'heavy.plate.pants', name: 'Heavy Plate Pants' },
    { id: 'attire.hide.boots', name: 'Hide Boots' },
    { id: 'attire.hide.helterneck', name: 'Hide Halterneck' },
    { id: 'attire.hide.pants', name: 'Hide Pants' },
    { id: 'attire.hide.poncho', name: 'Hide Poncho' },
    { id: 'attire.hide.skirt', name: 'Hide Skirt' },
    { id: 'attire.hide.vest', name: 'Hide Vest' },
    { id: 'hoodie', name: 'Hoodie' },
    { id: 'mask.balaclava', name: 'Improvised Balaclava' },
    { id: 'jacket', name: 'Jacket' },
    { id: 'largebackpack', name: 'Large Backpack' },
    { id: 'burlap.gloves', name: 'Leather Gloves' },
    { id: 'tshirt.long', name: 'Longsleeve T-Shirt' },
    { id: 'lumberjack hoodie', name: 'Lumberjack Hoodie' },
    { id: 'metal.plate.torso', name: 'Metal Chest Plate' },
    { id: 'metal.facemask', name: 'Metal Facemask' },
    { id: 'hat.miner', name: 'Miners Hat' },
    { id: 'nightvisiongoggles', name: 'Night Vision Goggles' },
    { id: 'pants', name: 'Pants' },
    { id: 'partyhat', name: 'Party Hat' },
    { id: 'riot.helmet', name: 'Riot Helmet' },
    { id: 'roadsign.gloves', name: 'Roadsign Gloves' },
    { id: 'roadsign.jacket', name: 'Road Sign Jacket' },
    { id: 'roadsign.kilt', name: 'Road Sign Kilt' },
    { id: 'shirt.collared', name: 'Shirt' },
    { id: 'pants.shorts', name: 'Shorts' },
    { id: 'smallbackpack', name: 'Small Backpack' },
    { id: 'jacket.snow', name: 'Snow Jacket' },
    { id: 'tactical.gloves', name: 'Tactical Gloves' },
    { id: 'shirt.tanktop', name: 'Tank Top' },
    { id: 'tshirt', name: 'T-Shirt' },
    { id: 'diving.wetsuit', name: 'Wetsuit' },
    { id: 'hat.wolf', name: 'Wolf Headdress' },
    { id: 'wood.armor.helmet', name: 'Wood Armor Helmet' },
    { id: 'wood.armor.pants', name: 'Wood Armor Pants' },
    { id: 'wood.armor.jacket', name: 'Wood Chestplate' }
],
tools: [
    { id: 'tool.binoculars', name: 'Binoculars' },
    { id: 'cakefiveyear', name: 'Birthday Cake' },
    { id: 'chainsaw', name: 'Chainsaw' },
    { id: 'flare', name: 'Flare' },
    { id: 'flashlight.held', name: 'Flashlight' },
    { id: 'hammer', name: 'Hammer' },
    { id: 'fishingrod.handmade', name: 'Handmade Fishing Rod' },
    { id: 'hatchet', name: 'Hatchet' },
    { id: 'jackhammer', name: 'Jackhammer' },
    { id: 'pickaxe', name: 'Pickaxe' },
    { id: 'pipetool', name: 'Pipe Tool' },
    { id: 'rf.detonator', name: 'RF Transmitter' },
    { id: 'rock', name: 'Rock' },
    { id: 'axe.salvaged', name: 'Salvaged Axe' },
    { id: 'hammer.salvaged', name: 'Salvaged Hammer' },
    { id: 'icepick.salvaged', name: 'Salvaged Icepick' },
    { id: 'explosive.satchel', name: 'Satchel Charge' },
    { id: 'grenade.smoke', name: 'Smoke Grenade' },
    { id: 'spraycan', name: 'Spray Can' },
    { id: 'stonehatchet', name: 'Stone Hatchet' },
    { id: 'stone.pickaxe', name: 'Stone Pickaxe' },
    { id: 'supply.signal', name: 'Supply Signal' },
    { id: 'explosive.timed', name: 'Timed Explosive Charge' },
    { id: 'torch', name: 'Torch' },
    { id: 'bucket.water', name: 'Water Bucket' }
],
medsAndTeas: [
    { id: 'antiradpills', name: 'Anti-Radiation Pills' },
    { id: 'bandage', name: 'Bandage' },
    { id: 'largemedkit', name: 'Large Medkit' },
    { id: 'syringe.medical', name: 'Medical Syringe' },
    
    { id: 'radiationresisttea.advanced', name: 'Advanced Anti-Rad Tea' },
    { id: 'healingtea.advanced', name: 'Advanced Healing Tea' },
    { id: 'maxhealthtea.advanced', name: 'Advanced Max Health Tea' },
    { id: 'oretea.advanced', name: 'Advanced Ore Tea' },
    { id: 'radiationremovetea.advanced', name: 'Advanced Rad. Removal Tea' },
    { id: 'scraptea.advanced', name: 'Advanced Scrap Tea' },
    { id: 'woodtea.advanced', name: 'Advanced Wood Tea' },
    { id: 'radiationresisttea', name: 'Anti-Rad Tea' },
    { id: 'healingtea', name: 'Basic Healing Tea' },
    { id: 'maxhealthtea', name: 'Basic Max Health Tea' },
    { id: 'oretea', name: 'Basic Ore Tea' },
    { id: 'scraptea', name: 'Basic Scrap Tea' },
    { id: 'woodtea', name: 'Basic Wood Tea' },
    { id: 'radiationresisttea.pure', name: 'Pure Anti-Rad Tea' },
    { id: 'healingtea.pure', name: 'Pure Healing Tea' },
    { id: 'maxhealthtea.pure', name: 'Pure Max Health Tea' },
    { id: 'oretea.pure', name: 'Pure Ore Tea' },
    { id: 'radiationremovetea.pure', name: 'Pure Rad. Removal Tea' },
    { id: 'scraptea.pure', name: 'Pure Scrap Tea' },
    { id: 'woodtea.pure', name: 'Pure Wood Tea' },
    { id: 'radiationremovetea', name: 'Rad. Removal Tea' }
],
trapsAndMiscellaneous: [
    { id: 'flameturret', name: 'Flame Turret' },
    { id: 'trap.landmine', name: 'Landmine' },
    { id: 'guntrap', name: 'Shotgun Trap' },
    { id: 'trap.bear', name: 'Snap Trap' },
    { id: 'spikes.floor', name: 'Wooden Floor Spikes' },
    
    { id: 'keycard_blue', name: 'Blue Keycard' },
    { id: 'door.key', name: 'Door Key' },
    { id: 'keycard_green', name: 'Green Keycard' },
    { id: 'fun.guitar', name: 'Guitar' },
    { id: 'note', name: 'Note' },
    { id: 'keycard_red', name: 'Red Keycard' }
],
components: [
    { id: 'fuse', name: 'Electric Fuse' },
    { id: 'propanetank', name: 'Empty Propane Tank' },
    { id: 'gears', name: 'Gears' },
    { id: 'metalblade', name: 'Metal Blade' },
    { id: 'metalpipe', name: 'Metal Pipe' },
    { id: 'metalspring', name: 'Metal Spring' },
    { id: 'riflebody', name: 'Rifle Body' },
    { id: 'roadsigns', name: 'Road Signs' },
    { id: 'rope', name: 'Rope' },
    { id: 'semibody', name: 'Semi Automatic Body' },
    { id: 'sewingkit', name: 'Sewing Kit' },
    { id: 'sheetmetal', name: 'Sheet Metal' },
    { id: 'smgbody', name: 'SMG Body' },
    { id: 'tarp', name: 'Tarp' },
    { id: 'techparts', name: 'Tech Trash' }
],
electrical: [
    { id: 'electric.andswitch', name: 'AND Switch' },
    { id: 'electric.audioalarm', name: 'Audio Alarm' },
    { id: 'autoturret', name: 'Auto Turret' },
    { id: 'electric.blocker', name: 'Blocker' },
    { id: 'electric.button', name: 'Button' },
    { id: 'ceilinglight', name: 'Ceiling Light' },
    { id: 'computerstation', name: 'Computer Station' },
    { id: 'electric.counter', name: 'Counter' },
    { id: 'electric.doorcontroller', name: 'Door Controller' },
    { id: 'electrical.branch', name: 'Electrical Branch' },
    { id: 'electric.furnace', name: 'Electric Furnace' },
    { id: 'electric.heater', name: 'Electric Heater' },
    { id: 'elevator', name: 'Elevator' },
    { id: 'electric.flasherlight', name: 'Flasher Light' },
    { id: 'fluid.combiner', name: 'Fluid Combiner' },
    { id: 'fluid.splitter', name: 'Fluid Splitter' },
    { id: 'fluid.switch', name: 'Fluid Switch & Pump' },
    { id: 'electric.hbhfsensor', name: 'HBHF Sensor' },
    { id: 'hosetool', name: 'Hose Tool' },
    { id: 'electric.igniter', name: 'Igniter' },
    { id: 'industrial.combiner', name: 'Industrial Combiner' },
    { id: 'industrial.conveyor', name: 'Industrial Conveyor' },
    { id: 'industrial.crafter', name: 'Industrial Crafter' },
    { id: 'industrial.splitter', name: 'Industrial Splitter' },
    { id: 'electric.battery.rechargable.large', name: 'Large Rechargeable Battery' },
    { id: 'electric.solarpanel.large', name: 'Large Solar Panel' },
    { id: 'electric.laserdetector', name: 'Laser Detector' },
    { id: 'electric.battery.rechargable.medium', name: 'Medium Rechargeable Battery' },
    { id: 'electrical.memorycell', name: 'Memory Cell' },
    { id: 'electric.orswitch', name: 'OR Switch' },
    { id: 'powered.water.purifier', name: 'Powered Water Purifier' },
    { id: 'electric.pressurepad', name: 'Pressure Pad' },
    { id: 'electric.random.switch', name: 'RAND Switch' },
    { id: 'target.reactive', name: 'Reactive Target' },
    { id: 'electric.rf.broadcaster', name: 'RF Broadcaster' },
    { id: 'rf_pager', name: 'RF Pager' },
    { id: 'electric.rf.receiver', name: 'RF Receiver' },
    { id: 'electrical.combiner', name: 'Root Combiner' },
    { id: 'searchlight', name: 'Search Light' },
    { id: 'electric.seismicsensor', name: 'Seismic Sensor' },
    { id: 'electric.sirenlight', name: 'Siren Light' },
    { id: 'electric.battery.rechargable.small', name: 'Small Rechargeable Battery' },
    { id: 'electric.fuelgenerator.small', name: 'Small Generator' },
    { id: 'electric.splitter', name: 'Splitter' },
    { id: 'electric.sprinkler', name: 'Sprinkler' },
    { id: 'storageadapter', name: 'Storage Adapter' },
    { id: 'storage.monitor', name: 'Storage Monitor' },
    { id: 'electric.switch', name: 'Switch' },
    { id: 'electric.teslacoil', name: 'Tesla Coil' },
    { id: 'electric.generator.small', name: 'Test Generator' },
    { id: 'electric.timer', name: 'Timer' },
    { id: 'waterpump', name: 'Water Pump' },
    { id: 'generator.wind.scrap', name: 'Wind Turbine' }
        // No coma al final
    ]
}; // Cerrar correctamente el objeto 'items'
